drop table if exists users;

CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL primary key,
    email VARCHAR(128) NOT NULL,
    password VARCHAR(128),
    roles VARCHAR(25),
    registration_Date TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
    );