
CREATE TABLE IF NOT EXISTS user_info (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL primary key,
    login VARCHAR(255),
    email VARCHAR(512) NOT NULL,
    password VARCHAR(255)
);

-- drop table if exists users, roles;

-- CREATE TABLE IF NOT EXISTS users (
--     id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL primary key,
--     login VARCHAR(255),
--     email VARCHAR(512) NOT NULL,
--     password VARCHAR(255),
--     registration_Date TIMESTAMP WITHOUT TIME ZONE,
--     CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
--     );
--
-- CREATE TABLE IF NOT EXISTS t_role (
--     id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL primary key,
--     name VARCHAR(50)
-- );